---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by iThorgrim.
--- DateTime: 24/07/2023 19:40
---
local AIO = AIO or require("AIO")
local Client = AIO.AddHandlers("WEEKLY_REWARDS", {})
local Controller = { }

local data = {
    Activities = {
        Raids = {
            [1] = { locked = false, claimed = true, item = 49319 },
            [2] = { locked = false, claimed = true, item = 49319 },
            [3] = { locked = false, claimed = true, item = 49319 },
        },

        Dungeons = {
            [1] = { locked = false, claimed = true, item = 49319 },
            [2] = { locked = false, claimed = true, item = 49319 },
            [3] = { locked = false, claimed = false, item = 49319 },
        },

        PvP = {
            [1] = { locked = true, claimed = true, item = 49319 },
            [2] = { locked = true, claimed = false, item = 49319 },
            [3] = { locked = true, claimed = false, item = 49319 },
        }
    },
}
local function SendUpdate(player, category, index)
    AIO.Handle(player, "AIO_WEEKLY_REWARDS", "Update", data, category, index)
end

function Controller.GivePlayerReward(player, item, amount)
    local isAdd = player:AddItem( item, amount )
    if ( not isAdd ) then
        SendMail( "Récompense Hebdomadaire", "Vous avez reçu une récompense pour avoir effectué les activités hebdomadaires.", player:GetGUIDLow(), 0, 41, 15, 0, 0, item, amount )
    end
end

function Controller.SetClaimed(player, category, index)
    data.Activities[category][index].claimed = true
end

function Client.SetReward(player, category, index)
    if ( data.Activities[category][index].locked or data.Activities[category][index].claimed ) then
        return
    end

    local item = data.Activities[category][index].item
    local amount = data.Activities[category][index].itemCount or 1

    data.Activities[category][index].claimed = true
    Controller.GivePlayerReward(player, item, amount)
    SendUpdate(player, category, index)
end

local function OnCommand(event, player, command)
    if (command == "showFrame") then
        AIO.Handle(player, "WEEKLY_REWARDS", "ShowFrame", data)
    end
end
RegisterPlayerEvent(42, OnCommand)